/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/sky': RouteRecordInfo<
      '/albums/sky',
      '/albums/sky',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fun/': RouteRecordInfo<
      '/fun/',
      '/fun',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girl/': RouteRecordInfo<
      '/girl/',
      '/girl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/C-C++-VSCode': RouteRecordInfo<
      '/posts/C-C++-VSCode',
      '/posts/C-C++-VSCode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gemini-tips': RouteRecordInfo<
      '/posts/gemini-tips',
      '/posts/gemini-tips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-usage-tutorial': RouteRecordInfo<
      '/posts/git-usage-tutorial',
      '/posts/git-usage-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github-home-bea-tutorial': RouteRecordInfo<
      '/posts/github-home-bea-tutorial',
      '/posts/github-home-bea-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github-student-certification': RouteRecordInfo<
      '/posts/github-student-certification',
      '/posts/github-student-certification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/IDM-activate-script': RouteRecordInfo<
      '/posts/IDM-activate-script',
      '/posts/IDM-activate-script',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/listen-to-songs-locally-for-free': RouteRecordInfo<
      '/posts/listen-to-songs-locally-for-free',
      '/posts/listen-to-songs-locally-for-free',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/resource-station': RouteRecordInfo<
      '/posts/resource-station',
      '/posts/resource-station',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/right-click-menu': RouteRecordInfo<
      '/posts/right-click-menu',
      '/posts/right-click-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/saladict-tips': RouteRecordInfo<
      '/posts/saladict-tips',
      '/posts/saladict-tips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/set-proxy-terminal': RouteRecordInfo<
      '/posts/set-proxy-terminal',
      '/posts/set-proxy-terminal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-usage-tutorial': RouteRecordInfo<
      '/posts/valaxy-usage-tutorial',
      '/posts/valaxy-usage-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vim-usage-tutorial': RouteRecordInfo<
      '/posts/vim-usage-tutorial',
      '/posts/vim-usage-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/win11-wsl2': RouteRecordInfo<
      '/posts/win11-wsl2',
      '/posts/win11-wsl2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Windows-installtion-system': RouteRecordInfo<
      '/posts/Windows-installtion-system',
      '/posts/Windows-installtion-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zotero-usage-tutorial': RouteRecordInfo<
      '/posts/zotero-usage-tutorial',
      '/posts/zotero-usage-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.4_@babel+parser_216c77d887101326cd799b09260e5c7d/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'pages/albums/sky.md': {
      routes:
        | '/albums/sky'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/fun/index.md': {
      routes:
        | '/fun/'
      views:
        | never
    }
    'pages/girl/index.md': {
      routes:
        | '/girl/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/C-C++-VSCode.md': {
      routes:
        | '/posts/C-C++-VSCode'
      views:
        | never
    }
    'pages/posts/gemini-tips.md': {
      routes:
        | '/posts/gemini-tips'
      views:
        | never
    }
    'pages/posts/git-usage-tutorial.md': {
      routes:
        | '/posts/git-usage-tutorial'
      views:
        | never
    }
    'pages/posts/github-home-bea-tutorial.md': {
      routes:
        | '/posts/github-home-bea-tutorial'
      views:
        | never
    }
    'pages/posts/github-student-certification.md': {
      routes:
        | '/posts/github-student-certification'
      views:
        | never
    }
    'pages/posts/IDM-activate-script.md': {
      routes:
        | '/posts/IDM-activate-script'
      views:
        | never
    }
    'pages/posts/listen-to-songs-locally-for-free.md': {
      routes:
        | '/posts/listen-to-songs-locally-for-free'
      views:
        | never
    }
    'pages/posts/resource-station.md': {
      routes:
        | '/posts/resource-station'
      views:
        | never
    }
    'pages/posts/right-click-menu.md': {
      routes:
        | '/posts/right-click-menu'
      views:
        | never
    }
    'pages/posts/saladict-tips.md': {
      routes:
        | '/posts/saladict-tips'
      views:
        | never
    }
    'pages/posts/set-proxy-terminal.md': {
      routes:
        | '/posts/set-proxy-terminal'
      views:
        | never
    }
    'pages/posts/valaxy-usage-tutorial.md': {
      routes:
        | '/posts/valaxy-usage-tutorial'
      views:
        | never
    }
    'pages/posts/vim-usage-tutorial.md': {
      routes:
        | '/posts/vim-usage-tutorial'
      views:
        | never
    }
    'pages/posts/win11-wsl2.md': {
      routes:
        | '/posts/win11-wsl2'
      views:
        | never
    }
    'pages/posts/Windows-installtion-system.md': {
      routes:
        | '/posts/Windows-installtion-system'
      views:
        | never
    }
    'pages/posts/zotero-usage-tutorial.md': {
      routes:
        | '/posts/zotero-usage-tutorial'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
